In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
#create array with array funtion using list
l=[1,2,3,4,5,6]
arr=np.array(l)
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [15]:
l=[]
for i in range(5):
    n=int(input("enter any number"))
    l.append(n)
arr=np.array(l)
print(arr)



enter any number 2
enter any number 3
enter any number 4
enter any number 5
enter any number 6


[2 3 4 5 6]


In [1]:
l1=[1,6,4,3,5]   # 1 6 64 81 25 #6 64
l2=[6,1,3,4,2]
l=[]
for i,j in zip(l1,l2):
    if(i**j)%2==0:
        l.append(i**j)
print(l)
    

[6, 64]


In [6]:
##array
arr=np.array([1, 2 ,3 ,4])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64


In [8]:
arr=np.array([[1, 2 ,3 ,4], [5,6,7,8], [9,10,11,12,]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
2
(3, 4)
12
int64


In [9]:

arr=np.array([[[1, 2 ,3 ,4]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[[[1 2 3 4]]]
<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int64


In [4]:
arr=np.array ([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
<class 'numpy.ndarray'>
3
(2, 2, 5)
20
int64


In [5]:
arr=np.array([[[1,2,3],[6,7,8],[3,5,6]],[[11,12,13],[16,17,18],[7,8,9]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)


[[[ 1  2  3]
  [ 6  7  8]
  [ 3  5  6]]

 [[11 12 13]
  [16 17 18]
  [ 7  8  9]]]
<class 'numpy.ndarray'>
3
(2, 3, 3)


In [12]:
 pip install flask


Note: you may need to restart the kernel to use updated packages.


In [13]:
pip install pyjokes

Note: you may need to restart the kernel to use updated packages.


In [14]:
import pyjokes

In [20]:
joke = pyjokes.get_joke()
print(joke)

As far as we know, our computer has never had an undetected error.
